remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
title: [The title of your site]
description: [A short description of your site's purpose]
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
